language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - "12"

git:
  depth: 3

script:
  - yarn test

notifications:
  email:
    reciepients:
      - jorgevelasquez006@hotmail.com
    on_success: always
    on_failure: always

deploy:
  provide: heroku

  skip-cleanup: true

  keep-history: true

  api_key: 1fde03c4-7dbe-4759-8401-a93b593d8d53
  app: platzi-store-backends
  on:
    repo: jorgevels/platzi-store-backend
